SELECT
  JSON_DATA:"state"::STRING AS STATE,
  JSON_DATA:"QualityOfLifeTotalScore"::NUMBER AS QUALITYOFLIFETOTALSCORE,
  JSON_DATA:"QualityOfLifeQualityOfLife"::NUMBER AS QUALITYOFLIFEQUALITYOFLIFE,
  JSON_DATA:"QualityOfLifeAffordability"::NUMBER AS QUALITYOFLIFEAFFORDABILITY,
  JSON_DATA:"QualityOfLifeEconomy"::NUMBER AS QUALITYOFLIFEECONOMY,
  JSON_DATA:"QualityOfLifeEducationAndHealth"::NUMBER AS QUALITYOFLIFEEDUCATIONANDHEALTH,
  JSON_DATA:"QualityOfLifeSafety"::NUMBER AS QUALITYOFLIFESAFETY
FROM {{ source('raw', 'QOL_JSON_RAW') }}