SELECT
  STATE,
  QUALITYOFLIFETOTALSCORE,
  QUALITYOFLIFEQUALITYOFLIFE,
  QUALITYOFLIFEAFFORDABILITY,
  QUALITYOFLIFEECONOMY,
  QUALITYOFLIFEEDUCATIONANDHEALTH,
  QUALITYOFLIFESAFETY
FROM TEAM_4_DB.REFINED.QOL_JSON_REFINED